# Generated by Django 5.0.14 on 2026-07-10 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['floor', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['building', 'level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['floor', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.UniqueConstraint(fields=('building', 'level', 'name'), name='unique_floor_per_building_level'),
        ),
        migrations.AddField(
            model_name='desk',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desks', to='spaces.floor'),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='spaces.floor'),
        ),
        migrations.AddIndex(
            model_name='desk',
            index=models.Index(fields=['floor', 'is_active'], name='spaces_desk_floor_i_7e8e83_idx'),
        ),
        migrations.AddConstraint(
            model_name='desk',
            constraint=models.UniqueConstraint(fields=('floor', 'name'), name='unique_desk_per_floor'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['floor', 'is_active'], name='spaces_room_floor_i_77916f_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('floor', 'name'), name='unique_room_per_floor'),
        ),
    ]
