# Generated by Django 5.0.14 on 2026-07-10 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
    atomic = False

    dependencies = [
        ('spaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('desk', 'Desk'), ('room', 'Room')], max_length=10)),
                ('booking_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('checked_in', 'Checked in'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('desk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='spaces.desk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booking_date', '-created_at'],
                'indexes': [models.Index(fields=['desk', 'booking_date', 'status'], name='booking_desk_date_status_idx')],
            },
        ),
        migrations.RunSQL(
            sql="""
                CREATE UNIQUE INDEX booking_user_date_desk_partial_uniq
                ON bookings_booking (user_id, booking_date)
                WHERE resource_type = 'desk'
                  AND status IN ('active', 'checked_in');
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS booking_user_date_desk_partial_uniq;
            """,
        ),
    ]
